### PR TITLE
Fix examples and dependencies in library.properties

### PR DESCRIPTION
**Pull request by T-vK**

### CODE REVIEW

**Comment by T-vK** [comment]
@FinianLandes Thanks for merging so quickly. :) I have a question regarding platform io. I see that version 1.1.0 is available, but 1.1.1 is not yet available. Is there another manual step you need to do in order to make the latest version available over there? https://registry.platformio.org/libraries/finianlandes/SpotifyEsp32

**Comment by FinianLandes** [comment]
No, youll just have to wait a bit it takes a second for PIO to update it, its weird, also i just found a few bugs in 1.1.1 so will fix those and upload 1.1.2 asap

**Comment by T-vK** [comment]
I see, thank you :+1:

**Comment by FinianLandes** [comment]
Btw if you want you can add me on discord and message me there thats a bit easier... https://discord.com/invite/ZTAFAjt5

**Pull request merged**
